basePath: /
definitions:
  model.Response:
    properties:
      message:
        type: string
      resultObj: {}
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server celler server.
  termsOfService: http://swagger.io/terms/
  title: Plata backend
  version: "1.0"
paths:
  /lastquotes:
    get:
      consumes:
      - application/json
      description: Get last quotes with time and rate
      parameters:
      - description: Сurrency code
        in: query
        name: CurrencyCode
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Response'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get last quotes rate with time
      tags:
      - Quotes
  /quotesbyid:
    get:
      consumes:
      - application/json
      description: Get Get quotes rate by id from redis
      parameters:
      - description: quotes
        in: query
        name: UpdateId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Response'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get quotes rate by id
      tags:
      - Quotes
  /updatequotes:
    post:
      consumes:
      - application/json
      description: Updating the quote in the background
      parameters:
      - description: Сurrency code
        in: query
        name: CurrencyCode
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Response'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Update Quotes Rate
      tags:
      - Quotes
swagger: "2.0"
